#!/bin/bash
#
# (C) Copyright IBM Corporation 2026
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This script starts the buildah-based build process for ubi-micro images.
# It sources buildah_build.sh after environment variables are set.
#
# Portions of this file were generated by IBM Bob.

# Get the absolute path of the script that is sourcing this file
# BASH_SOURCE[0] is this script (buildah_env.sh)
# BASH_SOURCE[1] is the script that sourced this one
if [ -z "${BASH_SOURCE[1]}" ]; then
	echo "Error: buildah_env.sh must be sourced from another script" >&2
	return 1
fi

# Get the absolute path of the sourcing script
SOURCING_SCRIPT="${BASH_SOURCE[1]}"

# If the path is relative, make it absolute
if [[ "$SOURCING_SCRIPT" != /* ]]; then
    SOURCING_SCRIPT="$(cd "$(dirname "$SOURCING_SCRIPT")" && pwd)/$(basename "$SOURCING_SCRIPT")"
fi

# Extract the directory path (remove the filename)
SCRIPT_DIR="$(dirname "$SOURCING_SCRIPT")"

# Extract UBI_VERSION (last directory component)
# e.g., from /path/to/21/jre/ubi-micro/ubi10 -> ubi10
UBI_VERSION="$(basename "$SCRIPT_DIR")"

# Extract UBI_BASE (second-to-last directory component)
# e.g., from /path/to/21/jre/ubi-micro/ubi10 -> ubi-micro
UBI_BASE="$(basename "$(dirname "$SCRIPT_DIR")")"

# Extract SEMERU_RUNTIME_KIND (third-to-last directory component)
# e.g., from /path/to/21/jre/ubi-micro/ubi10 -> jre
RUNTIME_KIND_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"
SEMERU_RUNTIME_KIND="$(basename "$RUNTIME_KIND_DIR")"

# Extract SEMERU_JAVA_VERSION (first directory component after repo root)
# e.g., from /path/to/21/jre/ubi-micro/ubi10 -> 21
# Navigate up 3 directories from SCRIPT_DIR to get the Java version
JAVA_VERSION_DIR="$(dirname "$(dirname "$(dirname "$SCRIPT_DIR")")")"
SEMERU_JAVA_VERSION="$(basename "$JAVA_VERSION_DIR")"

SEMERU_BINARY_BASE_URL="https://github.com/ibmruntimes"
SEMERU_BINARY_JAVA_VERSION_URL="$SEMERU_BINARY_BASE_URL/semeru$SEMERU_JAVA_VERSION-binaries/releases/download"

arch="$(uname -m)"
case "$arch" in
	aarch64|ppc64le|s390x)
		SEMERU_ARCH="$arch"
		;;
	x86_64)
		SEMERU_ARCH=x64
		;;
	*)
		echo "Error: Unrecognized (uname -m) arch: $arch" >&2
		return 1
		;;
esac

IMAGE="registry.access.redhat.com/$UBI_VERSION/$UBI_BASE"

CRIU_BINARY_BASE_URL="https://na.artifactory.swg-devops.com/artifactory/hyc-rt-java-delivery-generic-local/IBM/java/criu_build"
CRIU_BUILD_ID=101

# Source the buildah build script if we're building a ubi-micro image
if [ "$UBI_BASE" = "ubi-micro" ]; then
    REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    source "$REPO_ROOT/buildah_build.sh"
fi
