#!/bin/bash
#
# (C) Copyright IBM Corporation 2026
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This script implements the buildah-based build process for ubi-micro images.
# It is sourced by buildah_env.sh after environment variables are set.
#
# Portions of this file were generated by IBM Bob.

set -euo pipefail

# Semeru dependencies
SEMERU_PACKAGES="tzdata openssl ca-certificates fontconfig coreutils-single glibc-minimal-langpack glibc-langpack-en gzip tar"   
# CRIU dependencies
CRIU_PACKAGES="jansson libibverbs libmnl libnet libnftnl libpcap nftables protobuf-c"

# Trap to handle cleanup on error
trap 'cleanup $?' EXIT

CLEANUP_CONTAINERS=""
CLEANUP_IMAGES=""

cleanup() {
    # Cleanup containers
    if [ -n "$CLEANUP_CONTAINERS" ]; then
        for container in $CLEANUP_CONTAINERS; do
            buildah rm "$container" || true
        done
    fi

    # Cleanup images
    if [ -n "$CLEANUP_IMAGES" ]; then
        buildah rmi $CLEANUP_IMAGES || true
    fi
}

# BASH_SOURCE[0] is this script (buildah_build.sh)
# BASH_SOURCE[1] is the script that sourced this one
if [ -z "${BASH_SOURCE[1]}" ]; then
	echo "Error: buildah_build.sh must be sourced from another script" >&2
	return 1
fi

echo "======================================================================" >&2
echo "Building Semeru $SEMERU_EDITION $SEMERU_JAVA_VERSION $SEMERU_RUNTIME_KIND on $UBI_BASE $UBI_VERSION" >&2
echo "Target image: $FINAL_IMAGE_NAME" >&2
echo "======================================================================" >&2

echo "" >&2
echo "Stage 1: Creating base image with packages and CRIU..." >&2

base_container=$(buildah from "$IMAGE")
if [ -z "$base_container" ]; then
    echo "Error: Failed to create base container from $IMAGE" >&2
    return 1
fi

CLEANUP_CONTAINERS="$base_container $CLEANUP_CONTAINERS"

# Set environment variables
buildah config --env LANG='en_US.UTF-8' --env LANGUAGE='en_US:en' --env LC_ALL='en_US.UTF-8' "$base_container"

# Mount the container filesystem
base_mount_point=$(buildah mount "$base_container")
if [ -z "$base_mount_point" ]; then
    echo "Error: Failed to mount base container" >&2
    return 1
fi

echo "Installing base packages..." >&2

# Use dnf with --installroot to install into the container
if command -v dnf &> /dev/null; then
    echo "Installing packages..." >&2

    # Install minimal language support for system commands like bash, find, grep, etc.
    # This file exists in ubi-minimal containers and takes effect when packages are installed from within the container.
    # Since we're running dnf on the host, we need this file there.
    # If it existed previously we back it up and restore when done.
    rpm_macros_file="$HOME/.rpmmacros"
    mkdir -p "$(dirname "$rpm_macros_file")"
    [ -e "$rpm_macros_file" ] && echo "Backing up existing rpm macros" >&2 && cp "$rpm_macros_file" "$rpm_macros_file.bak"
    echo "Setting up temp rpm macros" >&2 && echo '%_install_langs C.utf8' >> "$rpm_macros_file"

    dnf install -y --installroot="$base_mount_point" --releasever="$base_mount_point" --setopt=install_weak_deps=False --setopt=tsflags=nodocs $SEMERU_PACKAGES $CRIU_PACKAGES >&2
    dnf --installroot="$base_mount_point" clean all >&2

    echo "Removing temp rpm macros" >&2 && rm -rf "$rpm_macros_file"
    [ -e "$rpm_macros_file.bak" ] && echo "Restoring backup rpm macros" >&2 && mv "$rpm_macros_file.bak" "$rpm_macros_file"

    # Leftovers from dnf
    rm -rf "$base_mount_point/var/cache/" "$base_mount_point/var/lib/rhsm/" "$base_mount_point/var/lib/rpm/" "$base_mount_point/var/log/"
else
    echo "Error: 'dnf' command not found" >&2
    return 1
fi

# Grab container's current PATH so we can add stuff to it later
CONTAINER_PATH=$(buildah run "$base_container" -- sh -c 'echo $PATH')

if [ "$SEMERU_JAVA_VERSION" -ne 8 ] && [ -f "$CRIU_SECRETS_FILE" ]; then
    echo "Installing CRIU..." >&2

    source "$CRIU_SECRETS_FILE"

    criu_url="${CRIU_BINARY_BASE_URL}/${CRIU_BUILD_ID}/${SEMERU_ARCH}_linux/${UBI_VERSION}/criu.tar.gz"
    criu_sha_url="${CRIU_BINARY_BASE_URL}/${CRIU_BUILD_ID}/${SEMERU_ARCH}_linux/${UBI_VERSION}/criu.tar.gz.sha256.txt"

    criu_host_download_path="/tmp"

    pushd "$criu_host_download_path"
    curl -H "${CRIU_AUTH_HEADER}" -LfsSo criu.tar.gz "${criu_url}"
    curl -H "${CRIU_AUTH_HEADER}" -LfsSo criu.tar.gz.sha256.txt "${criu_sha_url}"
    sha256sum -c criu.tar.gz.sha256.txt
    # Extract to container mount
    tar -xzf criu.tar.gz --strip-components=1 -C "$base_mount_point"
    popd

    echo /usr/local/lib64 > "$base_mount_point/etc/ld.so.conf.d/criu.conf"
    mkdir -p "$base_mount_point/opt/criu"
    cp "$base_mount_point/usr/local/sbin/criu" "$base_mount_point/opt/criu/criu"
    
    # Run ldconfig and setcap inside container (these need to run in container context)
    buildah run "$base_container" -- ldconfig
    buildah run "$base_container" -- setcap cap_checkpoint_restore,cap_sys_ptrace,cap_setpcap=eip /usr/local/sbin/criu
    buildah run "$base_container" -- setcap cap_checkpoint_restore,cap_setpcap=eip /opt/criu/criu
    
    # Cleanup
    rm -f "$criu_host_download_path/criu.tar.gz" "$criu_host_download_path/criu.tar.gz.sha256.txt"
    
    # Add CRIU to container's PATH
    buildah config --env PATH="/usr/local/sbin:${CONTAINER_PATH}" "$base_container"
else
    echo "Skipping CRIU installation" >&2
fi

manifest_file="$REPO_ROOT/semeru-binaries.txt"
# Search for matching line: edition|java_version|runtime_kind|arch|jvm_version|checksum|url
line=$(grep -v "^#" "$manifest_file" | grep "^${SEMERU_EDITION}|${SEMERU_JAVA_VERSION}|${SEMERU_RUNTIME_KIND}|${SEMERU_ARCH}|" || true)
if [ -z "$line" ]; then
    echo "Error: No binary found for: edition=$SEMERU_EDITION, java version=$SEMERU_JAVA_VERSION, kind=$SEMERU_RUNTIME_KIND, arch=$SEMERU_ARCH" >&2
    return 1
fi

# Parse the line
SEMERU_JVM_VERSION=$(echo "$line" | cut -d'|' -f5)
SEMERU_BINARY_CHECKSUM=$(echo "$line" | cut -d'|' -f6)
SEMERU_BINARY_URL=$(echo "$line" | cut -d'|' -f7)

echo "Installing Semeru Java runtime..." >&2

# Determine JAVA_HOME_PATH based on edition
if [ "$SEMERU_EDITION" = "certified" ]; then
    JAVA_HOME_PATH="/opt/ibm/java"
else
    JAVA_HOME_PATH="/opt/java/openjdk"
fi

echo "JVM Version: $SEMERU_JVM_VERSION" >&2
echo "Binary Checksum: $SEMERU_BINARY_CHECKSUM" >&2
echo "Binary URL: $SEMERU_BINARY_URL" >&2
echo "Architecture: $SEMERU_ARCH" >&2
echo "Java Home: $JAVA_HOME_PATH" >&2

# Download tarball to host
semeru_host_download_path="/tmp"
semeru_tarball="$semeru_host_download_path/openjdk.tar.gz"

if [ -f "$semeru_tarball" ]; then
    echo "Semeru tarball already exists, verifying checksum..." >&2
    semeru_existing_checksum=$(sha256sum "$semeru_tarball" | awk '{print $1}')
    if [ "$semeru_existing_checksum" = "$SEMERU_BINARY_CHECKSUM" ]; then
        echo "Checksum matches, using existing tarball" >&2
    else
        echo "Checksum mismatch, re-downloading..." >&2
        curl -LfsSo "$semeru_tarball" "$SEMERU_BINARY_URL"
    fi
else
    echo "Downloading Semeru tarball..." >&2
    curl -LfsSo "$semeru_tarball" "$SEMERU_BINARY_URL"
fi

# Verify checksum
echo "$SEMERU_BINARY_CHECKSUM *$semeru_tarball" | sha256sum -c - >&2

mkdir -p "$base_mount_point/licenses"

# Extract to container mount based on edition
if [ "$SEMERU_EDITION" = "certified" ]; then
    # Certified edition installs to /opt/ibm/java
    mkdir -p "$base_mount_point/opt/ibm"
    # TODO: Extract directly to /opt/ibm/java
    tar -xf "$semeru_tarball" -C "$base_mount_point/opt/ibm"
    mv "$base_mount_point/opt/ibm/jdk-"* "$base_mount_point/opt/ibm/java"
    if [ "$SEMERU_JAVA_VERSION" -ge 25 ]; then
        cp "$base_mount_point/opt/ibm/java/legal/java.base/license_en.txt" "$base_mount_point/licenses/"
    else
        cp "$base_mount_point/opt/ibm/java/legal/java.base/license/license_en.txt" "$base_mount_point/licenses/"
    fi
else
    # Open edition installs to /opt/java/openjdk
    mkdir -p "$base_mount_point/opt/java/openjdk"
    tar -xf "$semeru_tarball" --strip-components=1 -C "$base_mount_point/opt/java/openjdk"
    if [ "$SEMERU_JAVA_VERSION" -eq 8 ]; then
        cp "$base_mount_point/opt/java/openjdk/LICENSE" "$base_mount_point/licenses/"
    else
        cp "$base_mount_point/opt/java/openjdk/legal/java.base/LICENSE" "$base_mount_point/licenses/"
    fi
fi

# Cleanup
rm -f "$semeru_tarball"

# Set labels
buildah config \
    --label name="IBM Semeru Runtime" \
    --label vendor="International Business Machines Corporation" \
    --label version="$SEMERU_JVM_VERSION" \
    --label release="$SEMERU_JAVA_VERSION" \
    --label maintainer="jayasg12@in.ibm.com" \
    --label run="docker run --rm -ti <image_name:tag> /bin/bash" \
    --label summary="IBM Semeru Runtime Docker Image for OpenJDK with openj9 and ubi" \
    --label description="For more information on this image please see https://github.com/ibmruntimes/semeru-containers/blob/master/README.md" \
    "$base_container" >&2

# Set Java environment variables
buildah config \
    --env JAVA_VERSION="$SEMERU_JVM_VERSION" \
    --env JAVA_HOME="$JAVA_HOME_PATH" \
    --env PATH="$JAVA_HOME_PATH/bin:$CONTAINER_PATH" \
    --env JAVA_TOOL_OPTIONS="-XX:+IgnoreUnrecognizedVMOptions -XX:+PortableSharedCache -XX:+IdleTuningGcOnIdle -Xshareclasses:name=openj9_system_scc,cacheDir=/opt/java/.scc,readonly,nonFatal" \
    "$base_container"

# Commit base image
buildah unmount "$base_container" >&2    
base_image_name="${FINAL_IMAGE_NAME}-base"
buildah commit "$base_container" "$base_image_name" >&2
CLEANUP_IMAGES="$base_image_name $CLEANUP_IMAGES"

echo "Base image created: $base_image_name" >&2

echo "" >&2
echo "Stage 2: Generating SCC..." >&2

scc_container=$(buildah from "$base_image_name")
if [ -z "$scc_container" ]; then
    echo "Error: Failed to create SCC container from $base_image_name" >&2
    return 1
fi

CLEANUP_CONTAINERS="$scc_container $CLEANUP_CONTAINERS"

scc_mount_point=$(buildah mount "$scc_container")
if [ -z "$scc_mount_point" ]; then
    echo "Error: Failed to mount SCC container" >&2
    return 1
fi

echo "Installing Tomcat for SCC generation..." >&2

tomcat_version="9.0.115"
tomcat_checksum="8e6fa92883c161523269560a7dc9e8d58fd1199b29c630f681aa3ec2975b59d94674d2881331076b55f5ee0439748931d87c099c79d7bcea909303739e612e4b"
tomcat_filename="apache-tomcat-${tomcat_version}.tar.gz"
tomcat_host_download_path="/tmp"
tomcat_tarball="$tomcat_host_download_path/$tomcat_filename"
tomcat_install_path="/opt/tomcat-home"

mkdir -p "$scc_mount_point$tomcat_install_path"

# Download and check SHA if the tarball doesn't already exist, or it exists but SHA doesn't match
if [ ! -e "$tomcat_tarball" ] || ! echo "$tomcat_checksum $tomcat_tarball" | sha512sum -c - 2>/dev/null; then
    tomcat_success=
    for base_url in \
        https://dlcdn.apache.org/tomcat/tomcat-9/v${tomcat_version}/bin \
        https://archive.apache.org/dist/tomcat/tomcat-9/v${tomcat_version}/bin
    do
        if curl -LfsSo "$tomcat_tarball" "$base_url/$tomcat_filename" && [ -s "$tomcat_tarball" ]; then
            tomcat_success=1
            break
        fi
    done
    
    if [ -z "$tomcat_success" ]; then
        echo "Error: Failed to download Tomcat" >&2
        return 1
    fi
    
    echo "$tomcat_checksum $tomcat_tarball" | sha512sum -c - >&2
fi

# Extract to container mount
tar -xf "$tomcat_tarball" -C "$scc_mount_point$tomcat_install_path" --strip-components=1

echo "Generating SCC..." >&2

# SCC configuration
openj9_xshareclasses="-Xshareclasses:name=openj9_system_scc,cacheDir=/opt/java/.scc,bootClassesOnly"
openj9_java_options="-XX:+IProfileDuringStartupPhase $openj9_xshareclasses"
scc_size="64m"

echo "Calculating optimal SCC size..." >&2

# Create initial SCC
buildah run "$scc_container" -- java $openj9_xshareclasses,createLayer -Xscmx$scc_size -version

sleep_after_start=20
sleep_after_stop=5

echo "Starting/stopping Tomcat..." >&2
buildah run \
    --env OPENJ9_JAVA_OPTIONS="$openj9_java_options" \
    --env CATALINA_PID="$tomcat_install_path/tomcat.pid" \
    "$scc_container" -- sh -c "
    $tomcat_install_path/bin/startup.sh
    sleep $sleep_after_start
    $tomcat_install_path/bin/shutdown.sh -force
    sleep $sleep_after_stop
"

# Get the percentage full
full=$(buildah run "$scc_container" -- bash -c \
    "java $openj9_xshareclasses,printallStats 2>&1 || true" | \
    awk '/^Cache is [0-9.]*% .*full/ {print substr($3, 1, length($3)-1)}')
if [ -z "$full" ]; then
    echo "Warning: Could not determine SCC usage, using default size: $scc_size" >&2
    optimal_size="$scc_size"
else
    echo "SCC is $full% full" >&2

    # Calculate optimal size
    optimal_size=$(awk -v scc_size="$scc_size" -v full="$full" 'BEGIN {
        # Extract numeric part and suffix using gsub
        num = scc_size;
        suffix = "";
        if (match(scc_size, /[kmgtKMGT]$/)) {
            suffix = tolower(substr(scc_size, RSTART, RLENGTH));
            num = substr(scc_size, 1, RSTART - 1);
        }
        
        # Validate numeric part
        if (num !~ /^[0-9]+$/) {
            print "scc_size parameter is malformed: " scc_size > "/dev/stderr";
            exit 1;
        }
        
        size = num;
        if (suffix == "k") size *= 1024;
        else if (suffix == "m") size *= 1024*1024;
        else if (suffix == "g") size *= 1024*1024*1024;
        else if (suffix == "t") size *= 1024*1024*1024*1024;
        
        result = int(size * full / 100.0 + 0.5);
        print result;
    }')

    echo "Generating final SCC with optimal size: $optimal_size..." >&2
fi

buildah run "$scc_container" -- sh -c "java $openj9_xshareclasses,destroy || true" >&2

# Create final SCC with optimal size
buildah run "$scc_container" -- java $openj9_xshareclasses,createLayer -Xscmx$optimal_size -version >&2

echo "Starting/stopping Tomcat..." >&2
buildah run \
    --env OPENJ9_JAVA_OPTIONS="$openj9_java_options" \
    --env CATALINA_PID="$tomcat_install_path/tomcat.pid" \
    "$scc_container" -- sh -c "
    $tomcat_install_path/bin/startup.sh
    sleep $sleep_after_start
    $tomcat_install_path/bin/shutdown.sh -force
    sleep $sleep_after_stop
"

# Get final usage
full_percent=$(buildah run "$scc_container" -- bash -c \
    "java $openj9_xshareclasses,printallStats 2>&1 || true" | \
    awk '/^Cache is [0-9.]*% .*full/ {print substr($3, 1, length($3)-1)}')

echo "Final SCC is ${full_percent:-unknown}% full" >&2

rm -rf "$scc_mount_point$tomcat_install_path"

# Set SCC permissions
chmod -R 0777 "$scc_mount_point/opt/java/.scc"

echo "SCC generation completed" >&2

# Commit SCC image
buildah unmount "$scc_container" >&2
scc_image_name="${FINAL_IMAGE_NAME}-scc"
buildah commit "$scc_container" "$scc_image_name" >&2
CLEANUP_IMAGES="$scc_image_name $CLEANUP_IMAGES"

echo "SCC image created: $scc_image_name" >&2

echo "" >&2
echo "Stage 3: Generating InstantOn ldconfig cache..." >&2

ldconfig_container=$(buildah from "$scc_image_name")
if [ -z "$ldconfig_container" ]; then
    echo "Error: Failed to create ldconfig container from $scc_image_name" >&2
    return 1
fi

CLEANUP_CONTAINERS="$ldconfig_container $CLEANUP_CONTAINERS"

ldconfig_mount_point=$(buildah mount "$ldconfig_container")
if [ -z "$ldconfig_mount_point" ]; then
    echo "Error: Failed to mount ldconfig container" >&2
    return 1
fi

echo "Generating initial ldconfig cache..." >&2

buildah run "$ldconfig_container" -- ldconfig

# Find and remove glibc-hwcaps directories on mounted filesystem
glibc_hwcaps_dirs=$(buildah run "$ldconfig_container" -- ldconfig --print-cache | \
    sed --regexp-extended --silent 's,^.+[[:space:]]+=>[[:space:]]+(/.+/glibc-hwcaps)/.+$,\1,p' | \
    sort | uniq)

echo "Removing the following hwcaps directories: $glibc_hwcaps_dirs" >&2

for d in $glibc_hwcaps_dirs; do
    if [ -d "$ldconfig_mount_point$d" ]; then
        rm -rf "$ldconfig_mount_point$d"
    fi
done

echo "Generating final ldconfig cache..." >&2

# Regenerate ldconfig cache without hwcaps
buildah run "$ldconfig_container" -- ldconfig

# Commit ldconfig intermediate image
buildah unmount "$ldconfig_container" >&2
ldconfig_image_name="${FINAL_IMAGE_NAME}-ldconfig"
buildah commit "$ldconfig_container" "$ldconfig_image_name" >&2
CLEANUP_IMAGES="$ldconfig_image_name $CLEANUP_IMAGES"

echo "ldconfig image created: $ldconfig_image_name" >&2

# The final container is based on the SCC image rather than the ldconfig
# image because the ldconfig image modifies the base image and is therefore
# tainted. All we want from the ldconfig image is the ld.so.cache for instanton.
final_container=$(buildah from "$scc_image_name")
if [ -z "$final_container" ]; then
    echo "Error: Failed to create final container" >&2
    return 1
fi

CLEANUP_CONTAINERS="$final_container $CLEANUP_CONTAINERS"

# Copy instanton.ld.so.cache from ldconfig image
buildah copy --from "$ldconfig_image_name" "$final_container" /etc/ld.so.cache /etc/instanton.ld.so.cache >&2

# Set user to non-root
buildah config --user 1001 "$final_container" >&2

# Set default cmd as jshell for JDKs
if [ "$SEMERU_RUNTIME_KIND" = "jdk" ]; then
    buildah config --cmd "jshell" "$final_container" >&2
fi

# Commit final image
buildah commit "$final_container" "$FINAL_IMAGE_NAME" >&2

echo "Final image created: $FINAL_IMAGE_NAME" >&2
